---
node_exporter_os_user: "node-exporter"
node_exporter_os_group: "node-exporter"

# Local path to node exporter binary to upload to the hosts.
node_expoter_binary_path:

node_exporter_port: "9100"
node_exporter_web_listen_address: "0.0.0.0:{{ node_exporter_port }}"

node_exporter_enabled_collectors:
  - "systemd"

node_exporter_disabled_collectors: []

# Node exporter build version. Used in tests.
node_exporter_version:

# Specific source code commit hash. Used in tests.
node_exporter_release_commit:
