# Playbook prints hosts info.
---
- name: "Ansible hosts info"
  hosts: all
  gather_facts: yes
  tasks:
    - debug:
        msg:
          - "inventory_hostname: {{ inventory_hostname }}"
          - "ansible_hostname: {{ ansible_hostname }}"
          - "ansible_fqdn: {{ ansible_fqdn }}"
          - "ansible_host: {{ ansible_host }}"
